package com.harmonylift.ui.screens

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ArrowBack
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun PrivacyPolicyScreen(
    onBack: () -> Unit,
    modifier: Modifier = Modifier
) {
    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("PRIVACY POLICY.", style = MaterialTheme.typography.headlineMedium, fontWeight = FontWeight.Bold) },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(imageVector = Icons.Default.ArrowBack, contentDescription = "Back")
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = MaterialTheme.colorScheme.background,
                    titleContentColor = MaterialTheme.colorScheme.onBackground
                )
            )
        }
    ) { paddingValues ->
        Column(
            modifier = modifier
                .fillMaxSize()
                .background(MaterialTheme.colorScheme.background)
                .padding(paddingValues)
                .verticalScroll(rememberScrollState())
                .padding(24.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            Text(
                text = "Last Updated: July 18, 2026\nVersion: 5.1.0 (Production)",
                style = MaterialTheme.typography.bodyMedium,
                color = MaterialTheme.colorScheme.onSurfaceVariant
            )

            val policySections = listOf(
                "Offline-First Architecture" to "Harmony-Lift is built from the ground up to respect your privacy. Everything happens on your device.",
                "Local AI Inference & Llama.cpp" to "All AI features are powered by local models running on your hardware via Llama.cpp. We do not use cloud inference. Your data never leaves your device.",
                "Microphone Permissions" to "We require microphone access to analyze your instrument playing in real-time. Audio is processed locally and immediately discarded. It is never recorded or transmitted.",
                "Storage Permissions" to "We require storage access only to download and manage the local AI models (GGUF files) and to save your exported PDF/TXT reports.",
                "Exported Files" to "Any data you export (PDF/TXT) is generated locally. You have full control over where it is saved and who it is shared with.",
                "No Tracking & No Ads" to "We do not track your usage. We do not use analytics. We do not show advertisements. We do not sell your data.",
                "User Data Ownership" to "You own all data generated by this app. Your practice history, XP, and insights remain yours.",
                "Security Practices" to "Since all computation happens locally, the risk of data breaches is fundamentally minimized.",
                "Open-Source Acknowledgements" to "This application uses open-source libraries including Llama.cpp for AI inference and Android Jetpack components. We are deeply grateful to the open-source community.",
                "Contact Us" to "For privacy inquiries, please contact us at privacy@harmonylift.app."
            )

            policySections.forEach { (title, content) ->
                Text(
                    text = title,
                    style = MaterialTheme.typography.titleMedium,
                    fontWeight = FontWeight.Bold,
                    color = MaterialTheme.colorScheme.primary
                )
                Text(
                    text = content,
                    style = MaterialTheme.typography.bodyMedium,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
                Spacer(modifier = Modifier.height(8.dp))
            }
            
            Spacer(modifier = Modifier.height(32.dp))
        }
    }
}
